### ISSUE TITLE
Some codes may be conflict with paper

### ISSUE THREAD

**Issue by seanappler** [ymcui/Cross-Lingual-MRC#1]
Hi, 
https://github.com/ymcui/Cross-Lingual-MRC/blob/fea66c0859af8b13089a9af88ac54fc9f9f96691/src/layers.py#L374

I think here, input_tensor instead of source_input_tensor

**Comment by ymcui** [comment]
Hello,
Thank you for pointing out this issue.
There is a typo in the equation 7, where `LayerNorm(B_T + R)` should be replaced with `LayerNorm(B_S + R)`, as B_T will be concatenated afterwards (as in line https://github.com/ymcui/Cross-Lingual-MRC/blob/fea66c0859af8b13089a9af88ac54fc9f9f96691/src/layers.py#L376).

**Comment by seanappler** [comment]
Thanks for your reply.
