### ISSUE TITLE
Hello, if you do not have the data from the CMRC  test dataset, how do you translate them into the source language data? Thank you very much

### ISSUE THREAD

**Issue by zhangsanaixuexi** [ymcui/Cross-Lingual-MRC#2]

**Comment by ymcui** [comment]
Hi, 
as we are also the owner of the [CMRC 2018 dataset](http://github.com/ymcui/cmrc2018), we were able to create such data for evaluation. 
If you would like to compare to our results, you could compare against CMRC 2018 development set and DRCD dev/test sets.

**Comment by zhangsanaixuexi** [comment]
ok! Thank you very much!
